trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm audit fix
    ng build --prod
  displayName: 'Install Angular CLI, npm install, fix vulnerabilities, and build Angular app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/my-app-name'
    ArtifactName: 'dist'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
